allow debugging of files with build tags
leoluz/nvim-dap-go pull request #40
Opened 2023-03-26 12:24 UTC by debugloop

This should solve #35 and #36.

It is a bit more invasive than I would have liked for a first PR here, but the configuration needs to be accessible for the debug_test local function. If you don't like having the config as an attribute to the module object, I can rewrite this to expose additional `debug_test_with_buildflags(buildflags)` functions instead, but I actually think it is cleaner this way.

Thanks for the plugin, btw :)

2023-04-16 17:18 UTC, xD-saleem approved these changes

2023-04-16 17:20 UTC, xD-saleem commented
LGTM. this is amazing work.

2023-05-19 18:12 UTC, leoluz requested changes
Thank you for your contribution!
PR looks good. Can you please update the docs so I can merge?

2023-06-03 15:11 UTC, debugloop commented
Should have done so in the first place, thanks for the review. Since the latest additions around `args` and the default config var were merged, this PR is now a bit simpler overall :+1:

2023-07-17 15:16 UTC, leoluz approved these changes
LGTM

2023-07-17 15:16 UTC, merged