Allow configuration of dlv path
leoluz/nvim-dap-go pull request #47
Opened 2023-05-09 03:24 UTC by t-eckert

@leoluz, thank you so much for creating such a great DAP for Go. I use it every day at work.

I found that my installation was using a version of `dlv` I could not track down. I deleted every version from my `PATH` environment variable. It was stuck on a version `1.9` or so. It would be interesting to take you through what was going on there if you have any thoughts on what it could be.

Suffice it to say, I was unable to get the debugger working when I upgraded to Go 1.20 and needed to patch in my own path to the `dlv` executable. I figured I would submit the change I made upstream so that if others run into a similar problem, they can set the path to their `dlv` executable manually. This doesn't change the default behavior at all, just allows users to override the exectuable.

2023-05-19 19:47 UTC, leoluz requested changes
Thank you for your contribution!
Looking good so far. Please check my comment.
Could you also update the main documentation here?
https://github.com/leoluz/nvim-dap-go/blob/main/doc/nvim-dap-go.txt

2023-05-19 19:47 UTC, leoluz commented on README.md
> +    path_to_delve = "dlv",
We are already configuring the `delve` section. No need to repeat in the name of the variable `path_to_delve`. Just path is fine. 👍🏻

2023-05-22 16:48 UTC, t-eckert commented on README.md
> +    path_to_delve = "dlv",
Great! Made the changes. I tested it with both the default and a custom config and it worked in both cases.

2023-05-23 13:36 UTC, leoluz approved these changes
LGTM
Thank you!

2023-05-23 13:37 UTC, merged