attached debugging: filter process list
leoluz/nvim-dap-go pull request #57
Opened 2023-08-12 08:41 UTC by bitromortac

Thanks for the plugin! I used it successfully to attach to a process, however the process selection is tedious and time consuming scanning through the list of processes. Added a filter prompt to use the optional argument in `dap.utils.pick-process`.

2023-08-14 19:59 UTC, leoluz requested changes
Thank you for the contribution. I like your idea! Can you please just change the text in the prompt so users understand the behaviour not having to read the docs? Check my comment for a suggestion.

2023-08-14 19:59 UTC, leoluz commented on lua/dap-go.lua
> +  vim.ui.input({ prompt = "Filter process: " }, function(input)
Maybe a better prompt would be:
"Enter the process Id or hit enter to select from the list: "

2023-08-16 18:24 UTC, bitromortac commented on lua/dap-go.lua
> +  vim.ui.input({ prompt = "Filter process: " }, function(input)
Right, although it filters by the execution command (including flags), not by the process id as far as I can see. So I would go with "Enter process name or hit enter to select from the process list: ". One thing to notice is that it's a lua pattern, so we may need to auto-escape special chars, like `-`. Otherwise it won't match the entered process (for example it wouldn't match `my-process`). The alternative would be to keep it like it is but have the power of matching, but this may be more unintuitive.

2023-08-18 03:36 UTC, leoluz commented on lua/dap-go.lua
> +  vim.ui.input({ prompt = "Filter process: " }, function(input)
Good point! What about:
"Search by process name (lua pattern), or hit enter to select from the process list: "

2023-08-18 07:31 UTC, bitromortac commented on lua/dap-go.lua
> +  vim.ui.input({ prompt = "Filter process: " }, function(input)
Alright, done!

2023-08-18 16:08 UTC, merged