Add "Attach remote" config
leoluz/nvim-dap-go pull request #7
Opened 2022-05-23 23:12 UTC by shihanng

I am opening this pull request to add a new config called "Attach remote." I have use-cases where I want to debug CLI applications written in Go with specific flags or subcommands. Having "Attach remote," I can start the CLI using the following command,

```
dlv debug -l 127.0.0.1:38697 --headless ./cmd/main.go -- subcommand --flag=a
```

then connect to the debugger from Neovim using this new "mode". Please let me know what you think. Thank you.

2022-06-15 05:41 UTC, dapc11 requested changes

2022-06-15 05:41 UTC, dapc11 commented on lua/dap-go.lua
> +      end)
Could be extracted to a separate function

2022-06-15 05:41 UTC, dapc11 commented on lua/dap-go.lua
> +      local msg = string.format("connecting to server at '%s'...", addr)
Join these lines

2022-06-15 05:41 UTC, dapc11 commented on lua/dap-go.lua
> +    if (config.request == "attach" and config.mode == "remote") then
If-block could be it's own function

2022-07-03 14:11 UTC, nghialm269 commented
I have another use case for this: I develop go app in a docker container, so I have to run delve inside the docker container also. 

With this new configuration, I'd be able to attach to the remote delve instance to start debugging.

2022-11-01 03:43 UTC, leoluz commented
Sorry for the delay. Also, I need to configure this stalebot in a better way.

I understand your use-case and it seems a bit specific. I am not opposed to go ahead and add this new mode as long as it is well documented.

2022-11-01 04:02 UTC, leoluz reviewed
Thanks for your work and please take a look at my comments.

2022-11-01 04:02 UTC, leoluz commented on lua/dap-go.lua
> +    if (config.request == "attach" and config.mode == "remote") then
The if block (not the 'else') seems small enough to me. Not sure if it would be a good idea to break separate function just print a message. Or maybe I didn't understand your suggestion well @dapc11.

2022-11-01 12:24 UTC, shihanng commented on lua/dap-go.lua
> +      end)
@leoluz , if you don't feel strongly about this, I'd keep this as is.

2022-11-01 12:27 UTC, shihanng commented
@leoluz, thank you for the reviews and for reviving the PR :pray:. I've 
- resolved the merge conflict in [816fb5f](https://github.com/leoluz/nvim-dap-go/pull/7/commits/816fb5f16c7b21394a738655af1a60cee488f185)
- and added documentation in README [f1e0ee5](https://github.com/leoluz/nvim-dap-go/pull/7/commits/f1e0ee55596d88cab2d9c033a63328e7ce910094).

Let me know if there is anything else I can improve this PR. Thanks.

2022-11-04 00:16 UTC, leoluz approved these changes
LGTM

2022-11-04 00:16 UTC, merged