Set the Delve port dynamically for remote debug
leoluz/nvim-dap-go pull request #78
Opened 2024-04-10 08:20 UTC by cyb3rd4d

Currently the Delve port can be defined either randomly or hard-coded by hand.

Hard-coded port allows to know which port to use in remote debug configurations, but in practice with many Go projects, it would be great to set the Delve port in debug configurations.

Luckily `nvim-dap` allows to set an `on_config` callback for an adapter, which can be used to resolve the adapter settings when a debug session starts. This PR implements this `nvim-dap` feature, which can be used with the support of VSCode `launch.json` files to greatly enhance the developer experience.

This potentially resolves https://github.com/leoluz/nvim-dap-go/issues/73

2024-05-13 07:52 UTC, cyb3rd4d commented
Hello @leoluz, is it possible to get some feedback please?

2024-05-27 02:33 UTC, leoluz commented
> Hard-coded port allows to know which port to use in remote debug configurations, but in practice with many Go projects, it would be great to set the Delve port in debug configurations.

I am not sure that I understand exactly what is your use-case. You don't have to setup a different Delve port per Go project. They can all use the same port configuration unless you are trying to debug different Go projects at the same time. Can you please clarify what your use-case is?

2024-05-27 07:08 UTC, cyb3rd4d commented
I work on projects deployed on a local k8s cluster (k3d), most of them have a binary for an HTTP server others for workers (kafka consumers for example).

Also I always have multiple apps running in my cluster, each app is deployed in a development docker image with a its own delve port. Each port must be unique to be able to setup port forwarding on my local host.

It's really more convenient for me to keep the delve clients configuration inside my projects instead of having to set a long list of config entries in neovim's config.

2024-05-27 11:28 UTC, hippeus commented
Same here, I am looking forward to such addition. I have a setup that uses telepresence that randomly allocates a different free port so I can use it to debug my application inside a cluster with a very distributed system.

2024-07-04 20:53 UTC, leoluz commented
@cyb3rd4d Tks for the explanation. I'll try to review your PR soon.

2024-07-19 03:16 UTC, leoluz requested changes
Thank you for your contribution!
Can you please also update the `doc/nvim-dap-go.txt` file?

2024-07-19 03:16 UTC, leoluz commented on lua/dap-go.lua
> +    delve_config.port = client_config.port
Are we certain that `client_config.port` and `client_config.host` will always be defined at this point? Maybe it is better to add a validation and return a proper error message to the user in this case?

2024-07-19 08:22 UTC, cyb3rd4d commented
> Thank you for your contribution! Can you please also update the `doc/nvim-dap-go.txt` file?

Oh yes sorry I forgot this one!

2024-07-19 14:18 UTC, cyb3rd4d commented
I rebased and added config validation + completed the doc.

2024-07-20 02:04 UTC, leoluz requested changes
Thank you for the update. I added one more comment.

2024-07-20 02:04 UTC, leoluz commented on lua/dap-go.lua
> +    end
It seems that this is a breaking change as it forces the users to use the vscode configuration isn't it ? We want user's configurations to continue to work as before. Only in case the launch.json file is found that this validation needs to take place. Also, is this `mode` attribute part of the vscode config spec or something introduced by you?

2024-07-23 13:35 UTC, cyb3rd4d commented on lua/dap-go.lua
> +    end
> It seems that this is a breaking change as it forces the users to use the vscode configuration isn't it ?

Not really, the users still can use both the vscode configuration and the ones in their nvim config (and those you expose in the plugin). But this validation imposes to use the `port`, `host` and `mode` config keys no matter where the config is loaded from. So yes you're right for the breaking change, it's not acceptable.

Actually I think that no extra validation is needed, because your plugin does not validate the `dap_configurations` added by the users. If their is something wrong with a config, delve will return an error and it's OK from my point of view.

> Also, is this mode attribute part of the vscode config spec or something introduced by you?

The `mode` config key is already used in the plugin, I used the `remote` mode as described in your doc (section `dap-go-debug-headless`).
I think it's a VSCode thing, I could find a description here for the debug, test, exec and auto mode but not for the remote one: https://github.com/golang/vscode-go/wiki/debugging#launch

2024-07-23 13:47 UTC, cyb3rd4d commented on lua/dap-go.lua
> +    end
Actually the `mode` is passed to Delve, if I remove it from the DAP configuration I get an error: `2024-07-23T13:44:05Z debug layer=dap Failed to attach: debug session already in progress at [::]:4444 - use remote mode to connect to a server with an active debug session`

2024-07-28 00:09 UTC, leoluz commented on lua/dap-go.lua
> +    end
@cyb3rd4d My bad about the `mode` you are right. However I tested it locally and it is breaking the debug test functionality returning `missing DAP config key port` message. I also agree with you about removing the validation and allowing `nvim-dap`/`delve` to handle the config and return the error message accordingly. Let's just remove that validation and I'll give it another test.

Thank you and sorry for the back and forth.

2024-07-29 07:50 UTC, cyb3rd4d commented on lua/dap-go.lua
> +    end
> Thank you and sorry for the back and forth.

No problem! I do prefer taking the time to polish the feature rather than releasing something buggy or confusing ;)

Also, I missed this note from the Go VSCode extension doc:

> ⚠️ For ["Remote Debugging"](https://github.com/golang/vscode-go/wiki/debugging#remote-debugging), add the port attribute to the launch configuration. VS Code will connect to the external user-specified dlv dap server at host:port and launch the target there.

It would be nice I think if we reproduced this behavior: if the `port` config key is not nil, then run in remote mode. What do you think about that? The code would be like:

```lua
  dap.adapters.go = function(callback, client_config)
    if client_config.port == nil then
      callback(delve_config)
      return
    end

    local host = client_config.host
    if host == nil then
      host = "127.0.0.1"
    end

    local listener_addr = host .. ":" .. client_config.port
    delve_config.port = client_config.port
    delve_config.executable.args = { "dap", "-l", listener_addr }

    callback(delve_config)
  end
```

2024-07-31 00:48 UTC, leoluz commented on lua/dap-go.lua
> +    end
@cyb3rd4d cool. That looks much better! 
I ran a debug test with the code above and it is working as expected.

2024-07-31 07:40 UTC, cyb3rd4d commented on lua/dap-go.lua
> +    end
Great! I push the code ASAP

2024-08-06 01:37 UTC, leoluz approved these changes
LGTM
Thank you for contributing!

2024-08-06 01:38 UTC, merged