Add tests verbosity
leoluz/nvim-dap-go pull request #90
Opened 2024-06-17 17:23 UTC by gustavooferreira

I really like the feature of running the closest test to the cursor.

However, I usually make use of the `t.Logf` method which logs stuff when running tests. Without verbosity being turned on these logs will only show when the tests fail.

This PR adds an option to the plugin to enable verbosity. It sets this option to false by default so as to not change the behaviour of the plugin.

2024-06-18 13:33 UTC, hmajid2301 commented
This is a really cool feature!  would love to have this in dap-go.

2024-07-04 20:17 UTC, leoluz requested changes
Tks for contributing!
Just one doc request but overall looking good.

2024-07-04 20:17 UTC, leoluz commented on README.md
> +  },
can you please add this doc in the [nvim-dap-go.txt](https://github.com/leoluz/nvim-dap-go/blob/main/doc/nvim-dap-go.txt) file as well?

2024-07-09 21:48 UTC, gustavooferreira commented on README.md
> +  },
Hey Leo,

Yes, ofc, totally forgot about that one! Thanks for the reminder.

Docs have now been updated!

2024-07-19 02:37 UTC, leoluz approved these changes
LGTM
Tks for your contribution!

2024-07-19 02:53 UTC, merged