feat: add build as option for default list
leoluz/nvim-dap-go pull request #92
Opened 2024-07-03 18:43 UTC by nkane

#### Description
- add `get_build_flags` functions that works the same as `get_arguments` in order to get `go build` flags interactively.
- add default option `Debug (Arguments & Build Flags)` that will use interactive function to get build flags.

2024-07-04 20:51 UTC, leoluz requested changes
Tks for the PR.
Please update the documentation in the README.md and doc/nvim-dap-go.txt describing the new feature.

2024-07-04 20:51 UTC, leoluz commented on lua/dap-go.lua
> +    local build_flags = {}
I think the initial value of `build_flags` should be `configs.delve.build_flags` instead.

2024-07-04 20:51 UTC, leoluz commented on lua/dap-go.lua
> +    },
I don't think that we should add this as a default configuration but instead properly document the new `get_build_flags` function.

2024-07-05 19:56 UTC, nkane commented on lua/dap-go.lua
> +    local build_flags = {}
@leoluz, I messed around with trying to get this to be able to used from a config that someone might want to pass in but didn't come up with a good solution that worked properly. Basically, I was trying to be able to easily set the `go build` flags via a interactive prompt when debugging a program since I've got a project that has multiple build tags. How would you approach adding that functionality?

2024-07-05 20:31 UTC, nkane commented on lua/dap-go.lua
> +    local build_flags = {}
https://github.com/leoluz/nvim-dap-go/assets/6445086/5ec0f1ad-99f8-4320-ae44-1942b3ec462b

2024-07-06 01:13 UTC, nkane commented on lua/dap-go.lua
> +    local build_flags = {}
Alright, I think the most recent chain of commits might resolve the issues I was running in to. I'll update the readme / docs then squash the commits.

2024-07-19 02:32 UTC, leoluz approved these changes
LGTM
Thank you for your contribution!

2024-07-19 02:32 UTC, merged