feat: set cwd for dlv based on program
leoluz/nvim-dap-go pull request #99
Opened 2024-09-22 13:18 UTC by mcoqzeug

This potentially resolves #85.

vscode-go sets `dlv.executable.cwd` based on the value of `debug_config.program`. If `program` is a directory, `cwd` is set to `program`. If `program` is a path to a go file, `cwd` is set to its parent directory.

Reference: https://github.com/golang/vscode-go/blob/master/extension/src/goDebugConfiguration.ts#L545

2024-10-05 04:19 UTC, leoluz requested changes

2024-10-05 04:19 UTC, leoluz commented on lua/dap-go.lua
> +      local path = require("plenary.path")
This would introduce an external dependency to `plenary`. I prefer to keep the dependencies in this plugin as small as possible.

2024-10-17 01:28 UTC, leoluz commented on lua/dap-go.lua
> +      local path = require("plenary.path")
Thank you

2024-10-17 01:32 UTC, leoluz requested changes
@mcoqzeug  Thank you for removing plenary dependency.
I noticed that you are re-implementing file path logic that is already available as vim functions. The `get_parent` function for example can be replaced by `fnamemodify` (see https://stackoverflow.com/questions/16485748/how-to-get-the-parent-directory-of-a-path-string). Similar strategy can be used to extract the file extension with filename-modifier `:e` (see https://vimhelp.org/cmdline.txt.html#filename-modifiers)

2025-01-07 13:05 UTC, TendonT52 commented
Thank you, I'm just using this branch, and it works. Hope this will merge soon.

2025-02-03 03:18 UTC, leoluz requested changes
Hi @mcoqzeug . 
Thank you for the latest changes and fixes. PR is looking much cleaner now.
To proceed with the merge, the PR would need to include documentation updates in the `README.md` as well as in the `doc/[nvim-dap-go.txt` files
Thanks again!

2025-03-10 16:07 UTC, jinzhongjia commented
为什么不合并这个？然后更新文档

2025-03-10 17:33 UTC, mcoqzeug commented
> Hi @mcoqzeug . Thank you for the latest changes and fixes. PR is looking much cleaner now. To proceed with the merge, the PR would need to include documentation updates in the `README.md` as well as in the `doc/[nvim-dap-go.txt` files Thanks again!

Hi @leoluz, I think this PR only changes a small implementation detail and is compatible with existing documentation. The only change I can think of is to remove the `cwd` option from `REAME.md`: https://github.com/leoluz/nvim-dap-go/blob/main/README.md?plain=1#L90-L92. What do you think?

2025-03-24 04:59 UTC, kaldius commented on lua/dap-go.lua
> +        elseif vim.fn.fnamemodify(program_absolute, ":e") == ".go" then -- file extension is '.go'
Hi, @mcoqzeug I'm facing the same issue and your fork almost solved it for me, so thank you so much for this. I did notice that on my machine, `:lua print(vim.fn.fnamemodify("/a/b/c/main.go", ":e"))` returns `"go"` rather than `".go"`, so deleting the `.` in this line was the final step to get it working for me. 

Wondering if it's the same on your side?

Thanks again for your efforts and hope this PR gets merged soon!

2025-05-13 20:35 UTC, carlosflorencio commented
Also created https://github.com/leoluz/nvim-dap-go/pull/121 to fix this issue, unfortunately I've only noticed this PR afterwards.

2025-08-09 20:37 UTC, dennypenta commented
@leoluz does only missing documentation blocks us from merging it?

2025-12-10 04:43 UTC, closed without merging